--------------------------------------------------------
--  파일이 생성됨 - 수요일-2월-14-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRACKER
--------------------------------------------------------

  CREATE TABLE "C##TRACKER"."TRACKER" 
   (	"ID" NUMBER(38,0), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"AMOUNT" NUMBER(38,0), 
	"TRACKER_DATE" DATE, 
	"NOTE" VARCHAR2(255 BYTE), 
	"ICON" VARCHAR2(100 BYTE), 
	"CATEGORY_ID" NUMBER(38,0), 
	"ASSET_ID" NUMBER(38,0), 
	"USER_ID" NUMBER(38,0), 
	"TYPE_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EXPENSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TRACKER"."EXPENSE_PK" ON "C##TRACKER"."TRACKER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TRACKER
--------------------------------------------------------

  ALTER TABLE "C##TRACKER"."TRACKER" ADD CONSTRAINT "EXPENSE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRACKER
--------------------------------------------------------

  ALTER TABLE "C##TRACKER"."TRACKER" ADD CONSTRAINT "EXPENSE_CATEGORY_EX_FK" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "C##TRACKER"."CATEGORY" ("ID") ENABLE;
  ALTER TABLE "C##TRACKER"."TRACKER" ADD CONSTRAINT "TRACKER_ASSET_FK" FOREIGN KEY ("ASSET_ID")
	  REFERENCES "C##TRACKER"."ASSET" ("ID") ENABLE;
  ALTER TABLE "C##TRACKER"."TRACKER" ADD CONSTRAINT "TRACKER_TYPE_FK" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "C##TRACKER"."TYPE" ("ID") ENABLE;
  ALTER TABLE "C##TRACKER"."TRACKER" ADD CONSTRAINT "TRACKER_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##TRACKER"."APP_USER" ("NUM") ENABLE;
